name: Test and build channels
on:
  push:
    branches: [ "main", "channels" ]
  pull_request:
    branches: [ "main", "channels" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install flake8
    - name: Test with flake8
      run: |
        cd backend/channels && python -m flake8
    #- name: Build and run containers
    #  run: |
    #    cd backend/games && docker-compose up -d --build
        
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push broker
        uses: docker/build-push-action@v4
        with:
          context: ./backend/channels/broker
          # file: ./backend/channels/src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gspot-channels-broker:alpha
      -
        name: Build and push chat
        uses: docker/build-push-action@v4
        with:
          context: ./backend/channels/chat
          # file: ./backend/channels/src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gspot-channels-chat:alpha
