name: Build and test games
on:
  # push:
  #   branches: [ "main", "games" ]
  # pull_request:
  #   branches: [ "main", "games" ]
  push:
    branches: 
      - 'games'
      # - 'develop'
    paths:
      - 'backend/games/*'
jobs:
  test:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install flake8
    - name: Test with flake8
      run: |
        cd backend/games && python -m flake8
    #- name: Build and run containers
    #  run: |
    #    cd backend/games && docker-compose up -d --build
        
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/games
          file: ./backend/games/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gspot-games:latest
