name: Deploy payments to alpha server

on:
  workflow_run:
    workflows: 
      - 'Build and test payments'
    branches:
      - 'payments'
    types: 
      - completed
# on:
  push:
    branches: 
      - 'payments'
    paths:
      # - 'backend/payments/**'
      - '.cicd/composes/payments/**'
      - '.github/workflows/**'

jobs:
  deploy_payments:
    runs-on: alpha-server
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Docker pull image
      run: docker pull killla/gspot-payments:alpha
    - name: Docker-compose up
      run: |
        cp backend/payments/.env.example .cicd/composes/payments/.env
        cp backend/payments/docker-compose.yml .cicd/composes/payments/docker-compose.yml
        cd .cicd/composes/payments/
        docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
    - name: Send telegram message after deploy
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Deploy payments to alpha server finished
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}