name: Build and test users
on:
  push:
    branches: 
      - 'main'
      - 'users'
    paths:
      - 'backend/users/**'
  # pull_request:
  #   branches: [ "main", "users" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install flake8
    - name: Test with flake8
      run: |
        cd backend/users && python -m flake8
        
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/users
          # file: ./backend/users/docker/python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gspot-users:alpha
          cache-from: type=gha
          cache-to: type=gha,mode=max
